### PR TITLE
Expose xdg directories instead of home

### PR DESCRIPTION
**Pull request by cellscape**

### CODE REVIEW

**Comment by TingPing** [comment]
Seems like security theatre to me. It already gives full device access for example.

**Comment by cellscape** [comment]
Full device access doesn't mean user privileged process can read arbitrary files, disk devices are not readable by unprivileged users. Or am I missing something and with proposed changes skype will still be able to read dotfiles or browser history?

**Comment by cellscape** [comment]
Neither am I. IIRC wayland isolates keyboard input to process or window and doesn't let applications to capture images of other windows. As for passwords, I think it's possible to use different keyrings for different applications to restrict access.

Full device access usage is probably caused by limitations of flatpak/bubblewrap and this could be improved in future I believe.

I think even if we can't be sure of "total" security of some application it doesn't mean we shouldn't try to improve security. At the end it's your decision though.

**Comment by TingPing** [comment]
> IIRC wayland isolates keyboard input to process or window and doesn't let applications to capture images of other windows

Indeed, something Skype may not use for a few more years likely.

> As for passwords, I think it's possible to use different keyrings for different applications to restrict access.

Sure but Skype would need to stop using libsecret (or a new libsecret shim get created).

> Full device access usage is probably caused by limitations of flatpak/bubblewrap and this could be improved in future I believe

Yes the solution for this is Pipewire. Again it will be years before Skype ever comes near using it most likely.

> I think even if we can't be sure of "total" security of some application it doesn't mean we shouldn't try to improve security. At the end it's your decision though.

I won't out-right block this change. I just wanted to point out that it is only a fraction of getting this sandboxed.

**Comment by zarelit** [comment]
> Seems like security theatre to me. It already gives full device access for example.

Well there's not much one can do when trying to package a proprietary application AND trying to have the best UX out of the box. I think this is a nice balance because most of the applications for the desktop users already save their contents in the XDG directories and most of the applications save their secrets under some hidden directory in the user's home so this PR covers both the "share pictures with friends" scenario and the "don't allow Skype to fetch your passwords and keys by default" one.

@TingPing Since this also solves #26 and avoids having the whole home in read-only, could you please consider merging?

**Comment by TingPing** [comment]
@zarelit It already has write access to downloads, this changes nothing.

**Comment by zarelit** [comment]
@TingPing Even though it wouldn't solve #26 (it was a misconfiguration on my part), I still think it's a good idea to not give Skype access to `~/.ssh` `~/.config` and other locations where applications store secrets by default

**Comment by bacher09** [comment]
Hi, actually if someone wants to take home access from skype they can do it locally (instead of modifying package) by using `flatpack override`. 

For example:

    flatpak override --user --nofilesystem=home:ro --filesystem=xdg-documents \
            --filesystem=xdg-download --filesystem=xdg-music \
            --filesystem=xdg-pictures --filesystem=xdg-videoscom.skype.Client

Also, if someone wants he could gave even less permissions to skype (simply remove some `filesystem` options).
After this your override should look like this (note: *I gave less permissions for skype*):

    $ flatpak --user override --user --show com.skype.Client
    [Context]
    filesystems=!home;xdg-documents;xdg-music;xdg-download;

And to check permissions you can simply start shell in same namespace:

    $ flatpak run --user --command=/bin/bash  com.skype.Client


Hope this will be helpful for anyone who don't want to give `home:ro` permission to skype.

**Comment by rmader** [comment]
Small update as there has been some progress over the years:

> > IIRC wayland isolates keyboard input to process or window and doesn't let applications to capture images of other windows
> 
> Indeed, something Skype may not use for a few more years likely.
 
In a Wayland session X11/Xwayland clients can only see each other - not Wayland clients (and their inputs). I personally, on a Fedora 32, have few other X11 client left - Firefox, KeepassXC, Libreoffice, all Gnome apps - they all run natively on Wayland now and are therefore save(r) from spying.

> > As for passwords, I think it's possible to use different keyrings for different applications to restrict access.
> 
> Sure but Skype would need to stop using libsecret (or a new libsecret shim get created).

This was fixed in https://gitlab.gnome.org/GNOME/libsecret/-/merge_requests/6

> > Full device access usage is probably caused by limitations of flatpak/bubblewrap and this could be improved in future I believe
> 
> Yes the solution for this is Pipewire. Again it will be years before Skype ever comes near using it most likely.

Pipewire support is now an experimental feature in Chromium and apparently not too far out to get enabled by default (`chrome://flags/#enable-webrtc-pipewire-capturer`). This is also crucial to get screen capturing running in a Wayland session.

> > I think even if we can't be sure of "total" security of some application it doesn't mean we shouldn't try to improve security. At the end it's your decision though.
> 
> I won't out-right block this change. I just wanted to point out that it is only a fraction of getting this sandboxed.

Maybe we're slowly in a position where it actually does provide some benefit :)

**Comment by WhyNotHugo** [comment]
Are there any reasons to **not** merge this?

As mentioned above, the current defaults give Skype access to `.ssh` and `.config`, which is a huge security issue.

Sure, Skype can _potentially_ use some devices, but that's no reason to grant is access to secret keys as well.

**Comment by WhyNotHugo** [comment]
@cellscape Can you rebase this?

**Review by YoutacRSVARs — APPROVED** [review]

**Comment by FakeShemp** [comment]
Superseded by #170

**Pull request closed without merging**
