### PR TITLE
Update v8.18.76.1

### PR DESCRIPTION
**Pull request by LeandroStanger**

### CODE REVIEW

**Comment by jurf** [comment]
The release date in the AppData file needs to be bumped too.

**Comment by LeandroStanger** [comment]
https://github.com/flathub/com.skype.Client/pull/23

**Comment by TingPing** [comment]
@LeandroStanger Seriously you've done this a dozen times now and it is extremely frustrating. Please properly make and test changes locally and make a single correct PR. Just editing every versions online is not helpufl.

**Comment by barthalion** [comment]
This is preview release, 8.17.x is latest stable. Someone from IRC is going to make a pull request so closing this one for now.

**Pull request closed without merging**
